### ISSUE TITLE
Info about the Sega and Completed Screen.

### ISSUE THREAD

**Issue by Marteicos** [AlexIII/rings-of-saturn#1]
The screen is not even need to appear, the moment the System disc gets authenticated (even trhough a swap Trick inside cdplayer) the drive enters into the unlocked state.

If you power on holding the A button using the official system disc or your cut disc, the moment the Start application appears, the drive already accepts burned discs matching the System disc type used.

**Comment by AlexIII** [comment]
Hi! Thanks for the comment! I think I've already got that part in the text

> The "COMPLETED" message indicates that the DRM was disabled, however, if you don't see the message, it doesn't mean that the DRM inhibition has failed. In fact, it is not necessary to actually boot the System Disk. The magical part that disables the DRM is located in the TOC section of the System Disk, which is being read BEFORE the DRM check is performed.
